# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oBcaWT9l-67Huypd7SomYyAuyqD9_mqZ
"""

# !pip3 install tensorflow_text

import tensorflow_hub as hub
import numpy as np
import tensorflow_text

# ch_sen_1 = ['今天天气不错']
# ch_sen_2 = ['今天阳光明媚啊']
# ch_sen_3 = ['今天风和日期']
# ch_sen_4 = ['今天是晴空万里']

# ch_sen_5 = ['快下雨了']
# ch_sen_6 = ['今天是阴天啊']
# ch_sen_7 = ['天灰蒙蒙的']
# ch_sen_8 = ['太阳被乌云遮住了']

embed = hub.load('https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3')

ch_sen_1 = ['什么药可以治疗冠状病毒',
           '人会从动物那里感染2019冠状病毒病吗？']

ch_result_1 = embed(ch_sen_1)

# ch_sen_1_0 = ['天气 不错 哦',
#           '阳光 明媚 啊',
#           '快 下雨 了',
#           '是 阴天 啊',
#           '天 灰蒙蒙 的',
#           '太阳 被 乌云 遮住 了']

# ch_result_1_0 = embed(ch_sen_1_0)

# ch_result_1 = embed(ch_sen_1)

# ch_sen_2 = ['你多大了',
#             '你哪一年生的',
#             '你的家乡是哪里',
#             '你是哪里人',
#             '你做什么工作',
#             '你在哪里上班']

# ch_result_2 = embed(ch_sen_2)

# ch_sen_2_0 = ['你 多大 了',
#             '你 哪一年 生 的',
#             '你 的 家乡 是 哪里',
#             '你 是 哪里 人',
#             '你 做 什么 工作',
#             '你 在 哪里 上班']

# ch_result_2_0 = embed(ch_sen_2_0)


# ch_2_result = embed(ch_sen_2)
# ch_3_result = embed(ch_sen_3)
# ch_4_result = embed(ch_sen_4)
# ch_5_result = embed(ch_sen_5)
# ch_6_result = embed(ch_sen_6)
# ch_7_result = embed(ch_sen_7)
# ch_8_result = embed(ch_sen_8)

similarity_1 = np.inner(ch_result_1, ch_result_1)

print(similarity_1)
print(' ')

#similarity_1_0 = np.inner(ch_result_1_0, ch_result_1_0)

#print(similarity_1_0)

